name: hey_follow_up
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.3.0
  get_it: ^8.0.3
  injectable: ^2.1.1
  phone_number: ^2.1.0
  dotted_border: ^2.0.0+2
  cached_network_image: ^3.2.0
  country_icons: ^3.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  google_fonts: ^6.2.1
  image_picker: ^1.0.7
  provider: ^6.0.2
#  shared_preferences: ^2.5.2
  dio: ^5.4.1
  json_annotation: ^4.7.0
  internet_connection_checker: ^1.0.0+1
  shimmer: ^3.0.0
  another_flushbar: ^1.12.30
  path_provider: any
  pinput: ^5.0.1
  permission_handler: ^11.3.1
  url_launcher: ^6.2.6
  visibility_detector: ^0.4.0+2
#  flutter_share: ^2.0.0
  country_pickers: ^3.0.1
  country_picker: ^2.0.27
  camera: ^0.10.5+5


dev_dependencies:
  injectable_generator: ^2.4.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

dependency_overrides:
  #  flutter_stripe: "9.5.0+1"
  #  stripe_android: "9.5.0+1"
  #  stripe_ios: "9.5.0+1"
  #  stripe_platform_interface: "9.5.0+1"
  analyzer: ^4.7.0
  crypto: ^3.0.2
  http_parser: ^4.0.2
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  meta: ^1.8.0
  path: ^1.8.3
  xml:
  url_launcher: ^6.1.7
  package_info_plus: any
  flutter_spinkit: ^5.2.1
  another_flushbar: ^1.12.30
  shared_preferences: ^2.3.0

flutter_native_splash:
  color: "#f9f3f1"
  image: assets/images/logo.png
  android: true
  ios: true
  # android_gravity: true
  # ios_content_mode: scaleAspectFill

flutter_icons:
  image_path: assets/icons/launcher_icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
